### ISSUE TITLE
Link to all of a user's packages is broken

### ISSUE THREAD

**Issue by abadger** [fedora-infra/packagedb#1]
TG-1.1 uses a different format than  TG-1.0.  The old format is:
https://admin.fedoraproject.org/pkgdb/users/packages/sundaram?tg_paginate_limit=0

This is linked from a show all link on the users/packages page.

New format is:

https://admin.fedoraproject.org/pkgdb/users/packages/sundaram?pkgs_tgp_ordering=name&pkgs_tgp_limit=0

**Comment by pypingou** [comment]
Fixed then :)
