### ISSUE TITLE
Add previous_owner to the owner change fedmsg message.

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/packagedb#11]
This got merged in as a hotfix for pkgdb1

https://github.com/fedora-infra/packagedb/pull/10

This ticket is just a reminder to try and get that change merged into the pkgdb2 branch/tree too.

**Comment by pypingou** [comment]
maybe opening the ticket on pkgdb2 would work do it as well? :wink:

**Comment by ralphbean** [comment]
Where is that?

**Comment by ralphbean** [comment]
Done in fedora-infra/packagedb2#7
