### ISSUE TITLE
Allow to retire packages instead of only toggeling the retire status

### ISSUE THREAD

**Issue by tyll** [fedora-infra/packagedb#12]
The packagedb api only supports to toggle the retirement status, which is error-prone if some just wants to ensure that something is retired or used "fedpkg retire" to create a dead.package file of a branch that is already retired in packagedb.

It was tried to work around this on packagedb-cli, but imho any effort is better spend in adding support for retirement in packagedb, e.g. by adding a parameter to the toggle API named e.g. ensure_status with possible values "retired" and "unretired". In packagedb2 a cleaner API without toggle but only support to either retire or unretire a package could be introduced.

**Comment by abadger** [comment]
The devel-old branch of the current packagedb has a set_retirement() method.  I believe it also has changes to the javascript to use set_retirement() instead of toggle_retirement().

That code could be pulled into the present develop branch/

**Comment by ralphbean** [comment]
This looks like it is taken care of in the new packagedb2 code:

https://github.com/fedora-infra/pkgdb2/blob/master/pkgdb2/api/packages.py#L315-L471

We can likely close this issue once that is deployed to production.

**Comment by pypingou** [comment]
Let's close this :)
