### ISSUE TITLE
Check that the search field is not empty

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/packagedb#6]
If someone initiate a search without having provided a string to search for, we should maybe redirect to /list/ and show him an error message.

**Comment by ralphbean** [comment]
This looks to be fixed already in pkgdb2.  We can close it once that is deployed to production?

**Comment by pypingou** [comment]
No error message but it safely redirects, :+1: to close when we have pkgdb2

**Comment by pypingou** [comment]
And we have pkgdb2 now, closing :)
